name: kollektor_app
description: "Aplicación Flutter para gestión de cartera."
publish_to: 'none' # Mantén esto si es un proyecto privado.

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Manejo de estado (ejemplo: Provider)
  provider: ^6.0.0

  # Manejo de HTTP para APIs
  http: ^1.3.0

  # Manejo de bases de datos locales (ejemplo: Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Internacionalización (opcional)
  flutter_localizations:
    sdk: flutter

  # Logger actualizado
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter para buenas prácticas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Activos (imágenes, fuentes, etc.)
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo_kollektor.png
 
  # Fuentes personalizadas
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800